### ISSUE TITLE
Most features don't work 90% of the time

### ISSUE THREAD

**Issue by Cloudninjakip** [Gamebuster19901/InventoryDecrapifier#17]
Out of the features listed below that were found on the forum page, only the item glowing part actually works the way it is supposed to. Selecting certain items to pick up only works when looking at a very certain part of the dropped item. The stopping blacklisted items from entering your inventory doesn't work at all. Purging all blacklisted items from an opened container doesn't work either.
Ability to select which items you wish to pick up off the ground
Ability to make selected items glow
Ability to stop blacklisted items from entering your inventory
Ability to purge all blacklisted items from your inventory with a single keystroke
Ability to purge all blacklisted items from an opened container

**Comment by Cloudninjakip** [comment]
Also when purging items they sometimes glitch out and require you to press the keybind a few times for it to actually drop any items.

**Comment by Gamebuster19901** [comment]
I am unable to reproduce this. Can you post your client log? I suspect it's a mod conflict.

**Comment by Gamebuster19901** [comment]
Some features require the mod to be installed on the server for them to function.

'Ability to select which items you wish to pick up off the ground' requires server installation

'Ability to make selected items glow' should require server installation, however there is a bug where the item glows anyway

'Ability to stop blacklisted items from entering your inventory' requires server installation

'Ability to purge all blacklisted items from your inventory with a single keystroke' does not require server installation and works correctly in multiplayer and singleplayer. [You might have a poor keyboard](https://gaming.stackexchange.com/questions/6669/how-do-i-remove-the-limit-on-pc-keyboard-button-presses).

'Ability to purge all blacklisted items from your inventory with a single keystroke' does not require server installation and works fine.

'Ability to purge all blacklisted items from a container' does not require server installation, but requires you to press CTRL + [blacklist key] because some containers have text fields you can type into, such as anvils.
